# Site settings
title: "Earl Patrick Bellinger | Max Planck Institute for Astrophysics"
description: "Homepage of Earl Bellinger, postdoctoral research fellow working on asteroseismology"
baseurl: /

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Earl Patrick Bellinger, Ph.D."
resume_title:                   "Stellar Astrophysicist"
resume_contact_email:           "earlbellinger@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_teaching:        true
resume_section_publications:    true
resume_section_skills:          false
resume_section_talks:           true
resume_section_posters:         true
resume_section_misc:            true
resume_section_awards:          true
resume_section_press:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/earlbellinger"
  resume_twitter_url:           "https://twitter.com/earlbellinger"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://facebook.com/earlbellinger"
  resume_linkedin_url:          "https://www.linkedin.com/in/earlbellinger"
  #resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://soundcloud.com/earlbellinger/sets/music"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
